name: Send emails daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Run script
        env:
          ZOTERO_ID: 17503144
          ZOTERO_KEY: rHXFmxXIcCIUjoWYnAgYYjYl
          SENDER: 18874081210@163.com
          RECEIVER: LiaoJiaQi2019@163.com
          SENDER_PASSWORD: XAZPuSdpAdNEudGB
          OPENAI_API_KEY: sk-dELknMvndVGmRDunjNIenXjHbkAvVgzA4Uj4BXlXtHZpvB5w
          OPENAI_API_BASE: https://api.huiyan-ai.cn
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
        run: |
          printf "%b\n" "$CUSTOM_CONFIG" > config/custom.yaml
          echo "Use custom config: "
          cat config/custom.yaml
          uv run src/zotero_arxiv_daily/main.py
